name: Deploy Golden Minds Colleges Web System Project on push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and Build Vue.js Dependencies
        run: |
          npm install
          npm audit fix
          npm run build

      - name: Set appropriate permissions
        run: |
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache

      - name: Sync files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/.git/, /node_modules/, /tests/, /.github/, /phpunit.xml, /LICENSE, /README.md, /README.APPLICATION.md, /README.STANDARDS.md, /info.php"

      - name: Run remote commands
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            set -e
            cd ${{ secrets.REMOTE_TARGET }}
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            php artisan migrate --force
            php artisan optimize:clear
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          options: '-vvv -o KexAlgorithms=+diffie-hellman-group-exchange-sha256'